import biryani from "./assets/biryani.png";
import chinese from "./assets/chinese.png";
import continental from "./assets/continental.png";
import italian from "./assets/italian.png";
import mexican from "./assets/mexican.png";

const restaurants = [
  {
    resId: "1",
    name: "Spice 6",
    cuisine: "Indian",
    rating: "4.4 | 15-20 mins",
    approxBillForOne: "20$",
    img: biryani,
    promoted: true,
  },
  {
    resId: "2",
    name: "Pizza Palace",
    cuisine: "Italian",
    rating: "4.2 | 15-20 mins",
    approxBillForOne: "18$",
    img: chinese,
    promoted: false,
  },
  {
    resId: "3",
    name: "Sushi World",
    cuisine: "Japanese",
    rating: "4.6 | 15-20 mins",
    approxBillForOne: "25$",
    img: continental,
    promoted: true,
  },
  {
    resId: "4",
    name: "Burger Town",
    cuisine: "American",
    rating: "4.1 | 15-20 mins",
    approxBillForOne: "15$",
    img: italian,
    promoted: false,
  },
  {
    resId: "5",
    name: "Taco Fiesta",
    cuisine: "Mexican",
    rating: "4.3  | 15-20 mins",
    approxBillForOne: "12$",
    img: mexican,
    promoted: true,
  },
  {
    resId: "6",
    name: "Noodle House",
    cuisine: "Chinese",
    rating: "4.5  | 15-20 mins",
    approxBillForOne: "22$",
    img: chinese,
    promoted: true,
  },
  {
    resId: "7",
    name: "The Kebab Factory",
    cuisine: "MresIddle Eastern",
    rating: "4.7 | 15-20 mins",
    approxBillForOne: "24$",
    img: biryani,
    promoted: false,
  },
  {
    resId: "8",
    name: "Pasta Delight",
    cuisine: "Italian",
    rating: "4.0 | 15-20 mins",
    approxBillForOne: "17$",
    img: italian,
    promoted: true,
  },
  {
    resId: "9",
    name: "Curry Corner",
    cuisine: "Indian",
    rating: "4.3 | 15-20 mins",
    approxBillForOne: "19$",
    img: biryani,
    promoted: false,
  },
  {
    resId: "10",
    name: "Dim Sum Hub",
    cuisine: "Chinese",
    rating: "4.5 | 15-20 mins",
    approxBillForOne: "21$",
    img: chinese,
    promoted: true,
  },
  {
    resId: "11",
    name: "Burger Bros",
    cuisine: "American",
    rating: "4.2 | 15-20 mins",
    approxBillForOne: "16$",
    img: italian,
    promoted: false,
  },
  {
    resId: "12",
    name: "Falafel Feast",
    cuisine: "MresIddle Eastern",
    rating: "4.4 | 15-20 mins",
    approxBillForOne: "18$",
    img: continental,
    promoted: true,
  },
  {
    resId: "13",
    name: "Tempura House",
    cuisine: "Japanese",
    rating: "4.6 | 15-20 mins",
    approxBillForOne: "23$",
    img: continental,
    promoted: true,
  },
  {
    resId: "14",
    name: "Pizza Express",
    cuisine: "Italian",
    rating: "4.1 | 15-20 mins",
    approxBillForOne: "15$",
    img: italian,
    promoted: false,
  },
  {
    resId: "15",
    name: "Thai Spice",
    cuisine: "Thai",
    rating: "4. | 15-20 mins",
    approxBillForOne: "20$",
    img: continental,
    promoted: true,
  },
  {
    resId: "16",
    name: "Tandoori Flame",
    cuisine: "Indian",
    rating: "4.7 | 15-20 mins",
    approxBillForOne: "22$",
    img: biryani,
    promoted: false,
  },
  {
    resId: "17",
    name: "Salsa Grill",
    cuisine: "Mexican",
    rating: "4.3 | 15-20 mins",
    approxBillForOne: "13$",
    img: mexican,
    promoted: false,
  },
  {
    resId: "18",
    name: "Sushi Express",
    cuisine: "Japanese",
    rating: "4.4 | 15-20 mins",
    approxBillForOne: "24$",
    img: continental,
    promoted: false,
  },
  {
    resId: "19",
    name: "Barbecue Nation",
    cuisine: "Asian",
    rating: "4.8 | 05-10 mins",
    approxBillForOne: "20$",
    img: italian,
    promoted: false,
  },
  {
    resId: "20",
    name: "Pho Corner",
    cuisine: "Vietnamese",
    rating: "4.6 | 15-20 mins",
    approxBillForOne: "18$",
    img: continental,
    promoted: false,
  },
  {
    resId: "21",
    name: "Pho Corner",
    cuisine: "Vietnamese",
    rating: "4.6 | 15-20 mins",
    approxBillForOne: "18$",
    img: continental,
    promoted: false,
  },
];

export default restaurants;
